### ISSUE TITLE
Bad question

### ISSUE THREAD

**Issue by sjledet** [DigitalCurrencyCouncil/CertificationExam#7]
If the purpose of this question is to actually ascertain knowledge, then it needs to be more specific. If it is to confuse and cause plenty of people to answer wrong and just grow frustrated with the test, then keep it like it is.

I am assuming the purpose of this question is to separate Bitcoin 1.0 from Bitcoin 2.0 technologies. But it's still just confusing in the current form.

Why not ask something like "Which of the following could be considered Bitcoin 2.0 technology?"

Pick the odd one out:
-- Miners
-- Exchanges
-- Wallets
-- Payment processors
--\* Smart contracts

**Comment by DigitalCurrencyCouncil** [comment]
Thanks for the notes! The question has been reworded.
