### ISSUE TITLE
Requires speculation and conjecture

### ISSUE THREAD

**Issue by sjledet** [DigitalCurrencyCouncil/CertificationExam#8]
I feel this is another unsuitable question. It suggests an agenda and the appearance of impartiality. To ask test takes to conjecture what might happen is not appropriate. Ask in a way that says what the accusation is, if you must, but to just conjecture that there was something wrong and to state that for sure Monero and Litecon will never "come under SEC review" whatever that means, is just speculation. I am sure at least someone at the SEC has "reviewed" litecoin's initial offering, albeit informally, and this question is just rife with hypotheticals.

Some 'Bitcoin 2.0' platforms whose initial offerings may come under SEC review, are:
-- (a) Monero
-- (b) Counterparty
-- (c) Mastercoin
-- (d) Litecoin
-- (e) Ethereum
-- a and e
-- a, d, and e
--\* b, c, and e

**Comment by DigitalCurrencyCouncil** [comment]
Good points. Agreed. Question removed.
